# PR-01: Data Wrangling - I

# importing pandas for Data manipulation and analysis

In [20]:
import pandas as pd

# Load the dataset

In [21]:
df = pd.read_csv("NetflixOriginals.csv", encoding="latin-1")

# Display first 5 rows

In [22]:
df.head()

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58.0,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81.0,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79.0,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94.0,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90.0,3.4,Hindi

# Shape of dataset (rows, columns)

In [23]:
df.shape

(584, 6)

# Displays Column names

In [19]:
df.columns

Index(['Title', 'Genre', 'Premiere', 'Runtime', 'IMDB Score', 'Language'], dtype='object')

# Basic information about dataset

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       584 non-null    object
 1   Genre       584 non-null    object
 2   Premiere    584 non-null    object
 3   Runtime     581 non-null    float64
 4   IMDB Score  582 non-null    float64
 5   Language    580 non-null    object
dtypes: float64(2), object(4)
memory usage: 27.5+ KB

# Data types of each variable

In [4]:
df.dtypes

Title          object
Genre          object
Premiere       object
Runtime       float64
IMDB Score    float64
Language       object
dtype: object

# Check missing values in each column

In [5]:
df.isnull().sum()

Title         0
Genre         0
Premiere      0
Runtime       3
IMDB Score    2
Language      4
dtype: int64

# Summary statistics for numeric columns

In [23]:
df.describe()

          Runtime  IMDB Score
count  584.000000  584.000000
mean    93.577055    6.271747
std     27.761683    0.979256
min      4.000000    2.500000
25%     86.000000    5.700000
50%     97.000000    6.350000
75%    108.000000    7.000000
max    209.000000    9.000000

# Formating date to YYYY-MM-DD

In [18]:
 df['Premiere'] = pd.to_datetime(df['Premiere'], errors='coerce') #formatting date 
 df.head()

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,2019-08-05,58.0,2.5,English/Japanese
1,Dark Forces,Thriller,2020-08-21,81.0,2.6,Spanish
2,The App,Science fiction/Drama,2019-12-26,79.0,2.6,Italian
3,The Open House,Horror thriller,2018-01-19,94.0,3.2,English
4,Kaali Khuhi,Mystery,2020-10-30,90.0,3.4,Hindi

# Replace Imdb score with mean
IMDB Score is a continuous numerical variable that usually lies within a limited range (0–10) 
and tends to be approximately normally distributed.

The mean represents the average rating of all movies.
Replacing missing IMDB scores with the mean helps maintain the overall rating distribution.
Mean replacement does not introduce bias when the data has no extreme outliers.

In [24]:
df['IMDB Score'] = df['IMDB Score'].fillna(df['IMDB Score'].mean())

# Replace Runtime  with median 
Runtime is also a numerical variable, but it often contains outliers (very short or very long movies).

A few extremely long movies can skew the mean.
The median represents the middle value and is not affected by outliers.
Using the median ensures that missing runtime values are replaced with a typical movie length.

In [25]:
df['Runtime'] = df['Runtime'].fillna(df['Runtime'].median())

# Replace language with mode 
Language is a categorical (text-based) attribute, not numerical.

Mean and median cannot be applied to text data.
The mode represents the most frequently occurring language in the dataset.
Replacing missing language values with the mode preserves the most common language pattern in the data.

In [26]:
most_common_language = df['Language'].mode()[0]
df['Language'] = df['Language'].fillna(most_common_language)

# Checking missing values after null value replacement

In [27]:
df.isnull().sum()

Title         0
Genre         0
Premiere      0
Runtime       0
IMDB Score    0
Language      0
dtype: int64

# Convertsion of categorial data

In [31]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['Genre_encoded'] = encoder.fit_transform(df['Genre'])
df['Language_encoded'] = encoder.fit_transform(df['Language'])

 # Dropping cloumn Genre and language

In [32]:
df = df.drop(columns=['Genre', 'Language'])
df.head(15)

,Title,Premiere,Runtime,IMDB Score,Genre_encoded,Language_encoded
0,Enter the Anime,"August 5, 2019",58.0,2.500000,45,6
1,Dark Forces,"August 21, 2020",81.0,2.600000,106,29
2,The App,"December 26, 2019",79.0,2.600000,93,20
3,The Open House,"January 19, 2018",94.0,3.200000,63,2
4,Kaali Khuhi,"October 30, 2020",90.0,3.400000,73,18
5,Drive,"November 1, 2019",147.0,3.500000,0,18
6,Leyla Everlasting,"December 4, 2020",112.0,6.277491,32,37
7,The Last Days of American Crime,"June 5, 2020",149.0,3.700000,56,2
8,Paradox,"March 23, 2018",73.0,3.900000,72,2
9,Sardar Ka Grandson,"May 18, 2021",139.0,4.100000,32,18
10,Searching for Sheela,"April 22, 2021",58.0,4.100000,45,2
11,The Call,"November 27, 2020",112.0,4.100000,46,23
12,Whipped,"September 18, 2020",97.0,4.100000,81,19
13,All Because of You,"October 1, 2020",101.0,4.200000,1,24
14,Mercy,"November 22, 2016",90.0,4.200000,106,2