# Assignment 3A

# Import Python libraries

In [1]:
import pandas as pd

# Load the employee salary data

In [4]:
df = pd.read_csv("employee_salary_dataset.csv")
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

# Dataset Structure Inspection

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        50 non-null     int64
 1   Name              50 non-null     object
 2   Department        50 non-null     object
 3   Experience_Years  50 non-null     int64
 4   Education_Level   50 non-null     object
 5   Age               50 non-null     int64
 6   Gender            50 non-null     object
 7   City              50 non-null     object
 8   Monthly_Salary    50 non-null     int64
dtypes: int64(4), object(5)
memory usage: 3.6+ KB

# Grouping of age column

In [25]:
# Define age bins and labels
bins = [20, 30, 40, 50, 60]
labels = ["21-30", "31-40", "41-50", "51-60"]

# Create age_group column
df["age_group"] = pd.cut(df["Age"], bins=bins, labels=labels)

df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,age_group
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,51-60
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,21-30
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,51-60
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,41-50
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,31-40

# Sallary stastiscal Information

In [11]:
salary_stats = df_partA.groupby("age_group")["Monthly_Salary"].agg(
    Mean="mean",
    Median="median",
    Minimum="min",
    Maximum="max",
    Standard_Deviation="std"
)

salary_stats

/tmp/ipykernel_4779/3897078807.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  salary_stats = df_partA.groupby("age_group")["Monthly_Salary"].agg(

                   Mean   Median  Minimum  Maximum  Standard_Deviation
age_group
21-30      77864.266667  72333.0    28420   149123        40741.160001
31-40      85889.125000  74987.5    43711   132455        39280.697493
41-50      84999.375000  78106.0    30895   141381        26394.445337
51-60      81761.181818  70714.0    42429   134616        31708.178979

# Creating list for numeric response from each category

In [12]:
salary_list = df_partA.groupby("age_group")["Monthly_Salary"].apply(list)
salary_list

/tmp/ipykernel_4779/1652678848.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  salary_list = df_partA.groupby("age_group")["Monthly_Salary"].apply(list)

age_group
21-30    [95271, 31893, 72333, 28436, 122888, 30600, 11...
31-40    [132450, 44830, 55746, 132455, 127946, 81491, ...
41-50    [95091, 65818, 141381, 104909, 99290, 101213, ...
51-60    [111416, 69064, 70525, 42429, 44738, 79045, 70...
Name: Monthly_Salary, dtype: object

# Assigment 3B

# Import Python libraries

In [14]:
import pandas as pd

# Load the Iris dataset

In [16]:
df_iris = pd.read_csv("Iris.csv")
df_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Dataset Structure Inspection

In [17]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

# Statistical Information of SepalLengthCm and SepalWidthCm

In [29]:
iris_stats = df_iris.groupby("Species").describe()
iris_stats[['SepalLengthCm','SepalWidthCm']]

                SepalLengthCm                                              \
                        count   mean       std  min    25%  50%  75%  max
Species
Iris-setosa              50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor          50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica           50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                SepalWidthCm
                       count   mean       std  min    25%  50%    75%  max
Species
Iris-setosa             50.0  3.418  0.381024  2.3  3.125  3.4  3.675  4.4
Iris-versicolor         50.0  2.770  0.313798  2.0  2.525  2.8  3.000  3.4
Iris-virginica          50.0  2.974  0.322497  2.2  2.800  3.0  3.175  3.8

# Statistical Information of PetalLengthCm and PetalWidthCm

In [24]:
iris_stats[['PetalLengthCm','PetalWidthCm']]

                PetalLengthCm                                               \
                        count   mean       std  min  25%   50%    75%  max
Species
Iris-setosa              50.0  1.464  0.173511  1.0  1.4  1.50  1.575  1.9
Iris-versicolor          50.0  4.260  0.469911  3.0  4.0  4.35  4.600  5.1
Iris-virginica           50.0  5.552  0.551895  4.5  5.1  5.55  5.875  6.9

                PetalWidthCm
                       count   mean       std  min  25%  50%  75%  max
Species
Iris-setosa             50.0  0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor         50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica          50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5